hello:
  dev

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo
    username: root
    password: 1234567890
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379

rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: my-group

