hello:
  dev

spring:
  datasource:
    dynamic:
      primary: demo
      strict: true
      datasource:
        demo:
          url: jdbc:mysql://localhost:3306/demo
          username: root
          password: 1234567890
          driver-class-name: com.mysql.cj.jdbc.Driver
        test:
          url: jdbc:mysql://localhost:3306/test
          username: root
          password: 1234567890
          driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379

rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: my-group

liteflow:
  rule-source: config/flow.el.xml

